import { IdCard, CarFront, Car, Bus, Truck, DockIcon } from "lucide-react";

export const serviceConfig = {
  driverLicense: [
    {
      id: "fresh-3",
      category: "driverLicense",
      name: "Fresh",
      type: "3 years",
      price: 38000,
      icon: IdCard,
    },
    {
      id: "fresh-5",
      category: "driverLicense",
      name: "Fresh",
      type: "5 years",
      price: 45000,
      icon: IdCard,
    },
    {
      id: "renew-3",
      category: "driverLicense",
      name: "Renewal",
      type: "3 years",
      price: 26000,
      icon: IdCard,
      uploadRequired: 1,
      docName: ["Current Driver License"],
      fields: [],
    },
    {
      id: "renew-5",
      category: "driverLicense",
      name: "Renewal",
      type: "5 years",
      price: 30000,
      icon: IdCard,
      uploadRequired: 1,
      docName: ["Current Driver License"],
      fields: [],
    },
    {
      id: "intl-1",
      category: "driverLicense",
      name: "International (IDP)",
      duration: "1 year",
      price: 25000,
      icon: IdCard,
    },
  ],

  insurance: [
    {
      id: 1,
      name: "Saloon/Car",
      type: "Private",
      price: 23500,
      icon: CarFront,
    },
    {
      id: 2,
      name: "Saloon/Car",
      type: "Commercial",
      price: 26500,
      icon: CarFront,
    },
    { id: 3, name: "Jeep/SUV", type: "Private", price: 25000, icon: Car },
    {
      id: 4,
      name: "Space bus/Sienna",
      type: "Private",
      price: 25000,
      icon: Bus,
    },
    {
      id: 5,
      name: "Space bus/Sienna",
      type: "Commercial",
      price: 29200,
      icon: Bus,
    },
    {
      id: 6,
      name: "Pick-Up/Hilux",
      type: "Private",
      price: 27000,
      icon: Truck,
    },
    {
      id: 7,
      name: "Pick-Up/Hilux",
      type: "Commercial",
      price: 32000,
      icon: Truck,
    },
    {
      id: 8,
      name: "18 passenger/Bus",
      type: "Private",
      price: 26000,
      icon: Bus,
    },
    {
      id: 9,
      name: "18 passenger/Bus",
      type: "Commercial",
      price: 30000,
      icon: Bus,
    },
    { id: 10, name: "Coaster Bus", type: "Private", price: 30000, icon: Bus },
    {
      id: 11,
      name: "Coaster Bus",
      type: "Commercial",
      price: 35000,
      icon: Bus,
    },
    { id: 12, name: "Truck", type: "Commercial", price: 85000, icon: Truck },
  ],

  plateNumber: [
    {
      id: 1,
      name: "Private",
      type: "Saloon Car",
      desc: "(1.4–1.9L) – e.g. Golf, Corolla, Kia Rio, Civic",
      price: 75000,
      icon: DockIcon,
    },
    {
      id: 2,
      name: "Private",
      type: "Saloon Car",
      desc: "(2.0–2.6L) – e.g. Camry, Benz, Accord, Lexus & Others",
      price: 76500,
      icon: DockIcon,
    },
    {
      id: 3,
      name: "Commercial",
      type: "Saloon Car",
      desc: "(1.4–1.9L) – e.g. Golf, Corolla, Kia Rio, Civic",
      price: 78000,
      icon: DockIcon,
    },
    {
      id: 4,
      name: "Commercial",
      type: "Saloon Car",
      desc: "(2.0–2.6L) – e.g. Camry, Benz, Accord, Lexus & Others",
      price: 78000,
      icon: DockIcon,
    },
    {
      id: 5,
      name: "Private",
      type: "SUV | Jeep | Bus/Sienna | Pick-Up | Crossover",
      price: 78000,
      icon: DockIcon,
    },
    {
      id: 6,
      name: "Commercial",
      type: "SUV | Jeep | Bus | Pick-Up | Crossover",
      price: 83000,
      icon: DockIcon,
    },
    {
      id: 7,
      name: "Private",
      type: "Coaster Bus",
      price: 85000,
      icon: DockIcon,
    },
    {
      id: 8,
      name: "Commercial",
      type: "Coaster Bus",
      price: 89000,
      icon: DockIcon,
    },
    {
      id: 9,
      name: "Mini Trucks",
      type: "Trucks 15 Tons (Tippers)",
      price: 180000,
      icon: DockIcon,
    },
    {
      id: 10,
      name: "Trucks",
      type: "30 Tons (Trailers 10+ Tyres)",
      price: 180000,
      icon: DockIcon,
    },
  ],

  ownership: [
    {
      id: "1",
      icon: "fas fa-car",
      type: "Saloon/Car",
      category: "Private",
      price: 34000,
    },
    {
      id: "2",
      icon: "fas fa-car",
      type: "Saloon/Car",
      category: "Commercial",
      price: 37000,
    },
    {
      id: "3",
      icon: "fas fa-car-side",
      type: "SUV/Jeep",
      category: "Other",
      price: 36000,
    },
    {
      id: "4",
      icon: "fas fa-shuttle-van",
      type: "Space bus/Sienna",
      category: "Private",
      price: 35000,
    },
    {
      id: "5",
      icon: "fas fa-shuttle-van",
      type: "Space bus/Sienna",
      category: "Commercial",
      price: 38000,
    },
    {
      id: "6",
      icon: "fas fa-truck-pickup",
      type: "Pick-Up/Hilux",
      category: "Private",
      price: 36000,
    },
    {
      id: "7",
      icon: "fas fa-truck-pickup",
      type: "Pick-Up/Hilux",
      category: "Commercial",
      price: 38500,
    },
    {
      id: "8",
      icon: "fas fa-bus",
      type: "18 passenger/Bus",
      category: "Private",
      price: 35000,
    },
    {
      id: "9",
      icon: "fas fa-bus",
      type: "18 passenger/Bus",
      category: "Commercial",
      price: 38000,
    },
    {
      id: "10",
      icon: "fas fa-bus-alt",
      type: "Coaster Bus",
      category: "Private",
      price: 40000,
    },
    {
      id: "11",
      icon: "fas fa-bus-alt",
      type: "Coaster Bus",
      category: "Commercial",
      price: 42000,
    },
    {
      id: "12",
      icon: "fas fa-truck-moving",
      type: "Truck",
      category: "Other",
      price: 89580,
    },
  ],
};
